from content_engine.notion.client import (
    NotionClient,
    NotionClientConfig,
    NotionClientError,
    NotionDecodeError,
    NotionHTTPError,
)
from content_engine.notion.bootstrap import ensure_live_pipeline_targets
from content_engine.notion.payloads import (
    build_brief_properties,
    build_calendar_properties,
    build_content_performance_properties,
    build_draft_properties,
    build_feedback_signal_properties,
    build_filming_card_properties,
    build_idea_properties,
    build_insight_properties,
    build_orchestration_event_properties,
    build_script_properties,
    build_source_properties,
    build_video_publish_properties,
)
from content_engine.notion.sync import (
    ApprovalNotionTargets,
    ApprovalSyncResult,
    create_calendar_item,
    create_content_performance,
    create_idea,
    create_insight,
    create_feedback_signal,
    create_filming_card,
    create_orchestration_event,
    create_script,
    create_video_publish_item,
    sync_approval_result,
    upsert_brief,
    upsert_draft,
    upsert_source,
)


__all__ = [
    "NotionClient",
    "NotionClientConfig",
    "NotionClientError",
    "NotionDecodeError",
    "NotionHTTPError",
    "ensure_live_pipeline_targets",
    # payload builders
    "build_brief_properties",
    "build_calendar_properties",
    "build_content_performance_properties",
    "build_draft_properties",
    "build_feedback_signal_properties",
    "build_filming_card_properties",
    "build_idea_properties",
    "build_insight_properties",
    "build_orchestration_event_properties",
    "build_script_properties",
    "build_source_properties",
    "build_video_publish_properties",
    # sync functions
    "ApprovalNotionTargets",
    "ApprovalSyncResult",
    "create_calendar_item",
    "create_content_performance",
    "create_idea",
    "create_insight",
    "create_feedback_signal",
    "create_filming_card",
    "create_orchestration_event",
    "create_script",
    "create_video_publish_item",
    "sync_approval_result",
    "upsert_brief",
    "upsert_draft",
    "upsert_source",
]
